### ISSUE TITLE
设置cssModules转换规则后不生效

### ISSUE THREAD

**Issue by hjj1227** [Binbiubiubiu/taro-plugin-style-resource#3]
如果cssModules设置为true，转换模式设为module，该插件不生效，编译时会报全局设置的样式为undefined

```
cssModules: {
        enable: true, // 默认为 false，如需使用 css modules 功能，则设为 true
        config: {
          namingPattern: 'module', // 转换模式，取值为 global/module
          generateScopedName: '[name]__[local]___[hash:base64:5]'
        }
      }
```
报错：
🙅   编译失败. 2023/5/5 14:05:11

./src/components/goodsCard/index.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):

  overflow: hidden;
  .border-radius-md;
^
.border-radius-md is undefined

taro版本：3.3.12

**Comment by Binbiubiubiu** [comment]
fix in v0.1.10
